# Database Connection Configuration
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  # SMTP Server Configuration (email sending)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}

  # Google Cloud Storage and Vision Configuration
  cloud:
    gcp:
      project-id: ${GOOGLE_CLOUD_PROJECT}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Off DB Logs
logging:
  level:
    org.hibernate: warn
    com.zaxxer.hikari: warn