export const carBrands = [
    "Abarth", "Acura", "Aito", "Aiways", "Alfa Romeo", "Alpine", "Arcfox", "Asia", "Aston Martin", "Audi", "Austin", "Autobianchi", "AVATR",
    "Baic", "Bentley", "BMW", "BMW-ALPINA", "Brilliance", "Bugatti", "Buick", "BYD",
    "Cadillac", "Casalini", "Caterham", "Cenntro", "Changan", "Chatenet", "Chevrolet", "Chrysler", "Citroën", "Cupra",
    "Dacia", "Daewoo", "Daihatsu", "DeLorean", "DFM", "DFSK", "Dodge", "DR MOTOR", "DS Automobiles",
    "e.GO", "Elaris",
    "FAW", "Ferrari", "Fiat", "Fisker", "Ford", "Forthing",
    "Gaz", "Geely", "Genesis", "GMC", "GWM",
    "HiPhi", "Honda", "Hongqi", "Hummer", "Hyundai",
    "iamelectric", "Ineos", "Infinity", "Isuzu", "Iveco",
    "JAC", "Jaecoo", "Jaguar", "Jeep", "Jetour", "Jinpeng",
    "Kia", "Koenigsegg", "KTM",
    "Lada", "Lamborghini", "Lancia", "Land Rover", "Leapmotor", "LEVC", "Lexus", "Ligier", "Lincoln", "Lixiang", "Lotus", "LTI", "Lucid", "Lync & Co",
    "MAN", "Maserati", "Maxus", "Maybach", "Mazda", "McLaren", "Mercedes-Benz", "Mercury", "MG", "Microcar", "MINI", "Mitsubishi", "Morgan",
    "NIO", "Nissan", "Nysa",
    "Oldsmobile", "Omoda", "Opel",
    "Pagani", "Peugeot", "Piaggio", "Plymouth", "Polestar", "Polonez", "Pontiac", "Porsche",
    "RAM", "Renault", "Rimac", "Rolls-Royce", "Rover",
    "Saab", "SARINI", "Saturn", "Seat", "Seres", "Shuanghuan", "Skoda", "Skywell", "Skyworth", "Smart", "SsangYong", "Subaru", "Suzuki", "Syrena",
    "Tata", "Tesla", "Toyota", "Trabant", "Triumph",
    "Uaz", "Vauxhall", "Volkswagen", "Volvo", "Voyah", "Warszawa", "Wartburg", "Wołga",
    "Xiaomi", "XPeng",
    "Zaporożec", "Zastava", "ZEEKR", "Zenvo", "Zhidou"
];