export const carModels: Record<string, string[]> = {
    "Abarth": ["124", "500", "595", "695", "Grande Punto", "Punto Evo"],
    "Acura": ["CL", "Integra", "Legend", "MDX", "NSX", "RDX", "RL", "RSX", "TL", "TSX", "Vigor", "ZDX"],
    "Aito": ["M9"],
    "Aiways": ["U5", "U6"],
    "Alfa Romeo": ["4C", "33", "75", "90", "145", "146", "147", "155", "156", "159", "164", "166", "Alfasud", "Alfetta", "Brera", "Crosswagon", "Giulia", "Giulietta", "GT", "GTV", "Junior", "Mito", "RS", "Spider", "Sportwagon", "Sprint", "Stelvio", "Tonale"],
    "Alpine": ["A110", "A290"],
    "Arcfox": ["Alpha S5", "Alpha-S", "Alpha-T", "Kaola"],
    "Asia": ["Rocsta"],
    "Aston Martin": ["Bulldog", "Cygnet", "DB", "Db Mk III", "DB1", "DB2", "DB4", "DB5", "DB6", "DB7", "DB9", "DB11", "DB12", "DBS", "DBS Superleggera", "DBX", "DBX707", "Lagonda", "One-77", "Rapide", "V8", "V8 Vantage", "V8 Zagato", "V12 Vanquish", "V12 Vantage", "Vanquish", "Vantage", "Virage", "Volante"],
    "Audi": ["80", "90", "100", "200", "A1", "A2", "A3", "A4", "A4 Allroad", "A5", "A6", "A6 Allroad", "A7", "A8", "Cabriolet", "Coupe", "e-tron", "e-tron GT", "Q2", "Q3", "Q3 Sportback", "Q4", "Q4 Sportback", "Q5", "Q5 Sportback", "Q6", "Q7", "Q8", "Quattro", "R8", "RS e-tron GT", "RS Q3", "RS Q8", "RS2", "RS3", "RS4", "RS5", "RS6", "RS7", "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "SQ2", "SQ5", "SQ6", "SQ7", "SQ8", "TT", "TT RS", "TT S", "V8"],
    "Austin": ["Allegro", "Ambasador", "Healey", "Maxi", "Metro", "Mini", "Montego"],
    "Autobianchi": ["Bianchina"],
    "AVATR": ["11", "12"],
    "Baic": ["B40", "Beijing 3", "Beijing 5", "Beijing 7", "BJ20", "BJ40", "BJ60", "D20", "Senova X25", "Senova X35", "Senova X55", "Senova X65"],
    "Bentley": ["Arnage", "Azure", "Bentayga", "Brooklands", "Continental GT", "Eight", "Flying Spur", "Mulsanne", "Turbo R", "Turbo RT", "Turbo S"],
    "BMW": ["1M", "3GT", "5GT", "6GT", "i3", "i4", "i5", "i7", "i8", "iX", "iX1", "iX2", "iX3", "M2", "M3", "M4", "M5", "M6", "M8", "1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X3M", "X4", "X4M", "X5", "X5M", "X6", "X6M", "X7", "XM", "Z1", "Z3", "Z4", "Z4 M", "Z8"],
    "BMW-ALPINA": ["B3", "B4", "B5", "B6", "B7", "B8", "B10", "B12", "D3", "D4", "D5", "D10", "Roadster S", "XB7", "XD3", "XD4"],
    "Brilliance": ["BC3", "BS2", "BS4", "BS6"],
    "Bugatti": ["Chiron", "Divo", "EB 110", "Veyron"],
    "Buick": ["Centurion", "Century", "Electra", "Enclave", "Encore", "Lacrosse", "Le Sabre", "Lucerne", "Park Avenue", "Reatta", "Regal", "Rendezvous", "Riviera", "Roadmaster", "Skyhawk", "Skylark"],
    "BYD": ["Atto 2", "Atto 3", "Dolphin", "Dolphin Mini", "Han", "Seagull", "Seal", "Seal 6", "Seal U", "Sealion 5", "Sealion 7", "Song", "Tang", "Yuan"],
    "Cadillac": ["Allante", "ATS", "BLS", "Brougham", "Catera", "Cimarron", "CT4", "CT5", "CT6", "CTS", "Deville", "DTS", "Eldorado", "ELR", "Escalade", "Fleetwood", "Seville", "SLS", "SRX", "STS", "STS-V", "XLR", "XLR-V", "XT4", "XT5", "XT6", "XTS"],
    "Casalini": ["Kerry", "M10", "M12", "M14", "M14 2.0", "Pickup", "Sulky", "Ydea"],
    "Caterham": ["Academy", "CSR", "Roadsport", "Seven", "Super Seven"],
    "Cenntro": ["Avantier"],
    "Changan": ["UNI-K", "UNI-T", "UNI-V"],
    "Chatenet": ["CH22 Barooder", "CH26", "CH30", "CH32", "CH40", "CH46", "Media", "Speedino", "Sporteevo", "Stella"],
    "Chevrolet": ["1500", "2500", "3500", "Alero", "Apache", "Astro", "Avalanche", "Aveo", "Bel Air", "Beretta", "Blazer", "Bolt", "C-10", "C-20", "C-30", "Camaro", "Caprice", "Captiva", "Cavalier", "Celebrity", "Chevelle", "Chevy Van", "Citation", "Cobalt", "Colorado", "Corsica", "Corvette", "Cruze", "El Camino", "Epica", "Equinox", "Evanda", "Express", "G", "HHR", "Impala", "K30", "K1500", "Kalos", "Lacetti", "Lumina", "Malibu", "Matiz", "Monte Carlo", "Monza", "Nova", "Nubira", "Orlando", "Rezzo", "S-10", "Silverado", "Spark", "Spectrum", "SSR", "Suburban", "Tacuma", "Tahoe", "Trailblazer", "Trans Sport", "Traverse", "Trax", "Venture", "Volt"],
    "Chrysler": ["200", "300", "300C", "300M", "300s", "Aspen", "Caravan", "Concorde", "Crossfire", "Daytona", "ES", "Grand Voyager", "GS", "GTS", "Le Baron", "LHS", "Neon", "New Yorker", "Pacifica", "Prowler", "PT Cruiser", "Saratoga", "Sebring", "Stratus", "Town & Country", "Valiant", "Viper", "Vision", "Voyager"],
    "Citroën": ["2 CV", "AX", "Axel", "Berlingo", "BX", "C-Crosser", "C-Elysée", "C-Zero", "C1", "C2", "C3", "C3 Aircross", "C3 Picasso", "C3 Pluriel", "C4", "C4 Aircross", "C4 Cactus", "C4 Grand Picasso", "C4 Picasso", "C4 SpaceTourer", "C4X", "C5", "C5 Aircross", "C5X", "C6", "C8", "CX", "DS", "DS3", "DS4", "DS5", "DS7", "Evasion", "GSA", "Jumper", "Jumpy Combi", "Nemo", "Saxo" ,"SM", "SpaceTourer", "Visa", "Xantia", "XM", "Xsara", "Xsara Picasso", "ZX"],
    "Cupra": ["Ateca", "Born", "Formentor", "Leon", "Leon Sportstourer", "Tavascan", "Terramar"],
    "Dacia": ["1300", "1310", "1400", "1410", "Bigster", "Dokker", "Dokker Van", "Duster", "Jogger", "Lodgy", "Logan", "Logan Van", "Nova", "Pick Up", "Sandero", "Sandero Stepway", "Solenza", "Spring", "Super Nova"],
    "Daewoo": ["Chairman", "Cielo", "Espero", "Evanda", "Kalos", "Korando", "Lacetti", "Lanos", "Leganza", "Matiz", "Musso", "Nexia", "Nubira", "Racer", "Rezzo", "Tacuma", "Tico"],
    "Daihatsu": ["Applause", "Charade", "Charmant", "Copen", "Cuore", "Feroza", "Fourtrak", "Freeclimber", "Gran Move", "Hijet", "Materia", "Move", "Rocky", "Sirion", "Sportrak", "Terios", "Trevis", "YRV"],
    "DeLorean": ["DMC-12"],
    "DFM": ["Forthing 4", "Forthing 5"],
    "DFSK": ["Double Cab", "Fengon 5", "Fengon 7", "Fengon 500", "Fengon 580", "Glory 580", "Mini Bus", "Mini Van", "Pick Up", "Seres 3", "Seres 5"],
    "Dodge": ["Avenger", "Caliber", "Caravan", "Challenger", "Charger", "Dakota", "Dart", "Daytona", "Diplomat", "Durango", "Dynasty", "Grand Caravan", "Hornet", "Interpid", "Journey", "Magnum", "Monaco", "Neon", "Nitro", "Omni", "RAM", "RAM TRX", "Spirit", "Stealth", "Stratus", "Viper"],
    "DR MOTOR": ["DR 1.0", "DR 3.0", "DR 5.0", "DR 6.0"],
    "DS Automobiles": ["DS 3", "DS 3 Crossback", "DS 4", "DS 4 Crossback", "DS 5", "DS 7 Crossback", "DS 9"],
    "e.GO": ["e.wave X", "Life 20", "Life 40", "Life 60"],
    "Elaris": ["BEO", "DYO", "JACO", "Lenn", "LEO", "Pio"],
    "FAW": ["HQ"],
    "Ferrari": ["Daytona SP3", "208", "248", "250", "288", "296 GTB", "296 GTS", "308", "328", "330", "348", "360", "365", "400", "412", "456", "458 Italia", "458 Speciale", "488", "488 Pista", "488 Pista Spider", "512", "575", "599GTB", "612", "750", "812 GTS", "812 Superfast", "California", "California T", "Daytona", "Dino GT4", "Enzo", "F8 Spider", "F8 Tributo", "F12berlinetta", "F40", "F50", "F355", "F360", "F430", "F550", "FF", "GTC4Lusso", "LaFerrari", "Mondial", "Portofino", "Portofino M", "Purosangue", "Roma", "Roma Spider", "SF90 Spider", "SF90 Stradale", "Superamerica", "Testarossa"],
    "Fiat": ["124", "124 Spider", "125p", "126", "127", "128", "130", "131", "132", "500", "500e", "500L", "500X", "600", "850", "Albea", "Barchetta", "Brava", "Bravo", "Cinquecento", "Coupe", "Croma", "Dino", "Doblo", "Ducato", "Fiorino", "Freemont", "Fullback", "Grande Punto", "Idea", "Linea", "Marea", "Multipla", "Palio", "Panda", "Punto", "Punto 2012", "Punto Evo", "Qubo", "Regata", "Ritmo", "Scudo", "Sedici", "Seicento", "Siena", "Spider Europa", "Stilo", "Strada", "Talento", "Tempra", "Tipo", "Ulysse", "Uno", "X 1"],
    "Fisker": ["Karma"],
    "Ford": ["Aerostar", "Aspire", "B-MAX", "Bronco", "C-MAX", "Capri", "Contour", "Cougar", "Courier", "Crown", "Econoline", "Econovan", "EcoSport", "Edge", "Escape", "Escort", "Excursion", "Expedition", "Explorer", "F150", "F250", "F350", "Fairlane", "Falcon", "Festiva", "Fiesta", "FIVE HUNDRED", "Flex", "Focus", "Focus C-Max", "Freestar", "Fusion", "Galaxy", "Granada", "Grand C-MAX", "GT", "KA", "Ka+", "Kuga", "Maverick", "Mercury", "Mondeo", "Mustang", "Mustang Mach-E", "Orion", "Probe", "Puma", "Ranchero", "Ranger", "Ranger Raptor", "S-Max", "Scorpio", "Sierra", "Streetka", "Taunus", "Taurus", "Tempo", "Thunderbird", "Tourneo Connect", "Tourneo Connect Grand", "Tourneo Courier", "Tourneo Custom", "Transit", "Transit Connect", "Transit Courier", "Transit Custom", "Windstar"],
    "Forthing": ["T5 EVO", "U Tour"],
    "Gaz": ["67", "69"],
    "Geely": ["Azkarra", "Ck", "Coolray", "Emgrand", "Geometry C", "Geometry M6", "Monjaro", "New Coolray", "Okavango", "Tugella"],
    "Genesis": ["Electrified G80", "Electrified GV70", "G70", "G80", "G90", "GV60", "GV70", "GV80"],
    "GMC": ["Acadia", "Envoy", "Safari", "Savana", "Sierra", "Sonoma", "Syclone", "Terrain", "Typhoon", "Vandura", "Yukon"],
    "GWM": ["Altul", "Cowry", "Haval H5", "Hover", "Steed", "Voleex"],
    "HiPhi": ["A", "X", "Y", "Z"],
    "Honda": ["Accord", "Aerodeck", "City", "Civic", "Clarity", "Concerto", "CR-V", "CR-Z", "CRX", "e", "e:NP1", "e:NSP1", "e:NY1", "Element", "FR-V", "HR-V", "Insight", "Integra", "Jazz", "legend", "Logo", "NSX", "Odyssey", "Pilot", "Prelude", "Ridgeline", "S 2000", "Shuttle", "Stream", "ZR-V"],
    "Hongqi": ["E-HS9", "H5", "H7", "H9", "HS5", "HS7"],
    "Hummer": ["H1", "H2", "H3"],
    "Hyundai": ["Accent", "Atos", "Avante", "Azera", "Bayon", "Coupe", "Elantra", "Equus", "Excel", "Galloper", "Genesis", "Genesis Coupe", "Getz", "Grand Santa Fe", "Grandeur", "H-1", "H-1 Starex", "H200", "H350", "i10", "i20", "i25", "i30", "i30 N", "i40", "Inster", "IONIQ", "IONIQ 5", "IONIQ 6", "IONIQ 7", "ix20", "ix35", "ix55", "Kona", "Lantra", "Matrix", "NEXO", "Palisade", "Pony", "S-Coupe", "Santa Cruz", "Santa Fe", "Santamo", "Sonata", "Sonica", "Staria", "Tarracan", "Trejet", "Tucson", "Veloster", "Veracruz", "XG 30", "XG 350"],
    "iamelectric": ["ARIEL4", "SHARK"],
    "Ineos": ["Grenadier", "Quartermaster"],
    "Infinity": ["EX", "FX", "G", "I30", "I35", "J30", "M", "Q30", "Q45", "Q50", "Q60", "Q70", "QX", "QX30", "QX50", "QX60", "QX70", "QX80"],
    "Isuzu": ["Campo", "D-Max", "Gemini", "Midi", "Pick up", "Trooper"],
    "Iveco": ["Daily", "Massif"],
    "JAC": ["e-J7", "e-JS1", "e-JS4", "J6", "J7", "JS2", "JS3", "JS4", "JS6", "JS7", "JS8", "T6", "T8 PRO", "T9"],
    "Jaecoo": ["5", "7", "9"],
    "Jaguar": ["Daimler", "E-Type", "E-Pace", "F-Type", "I-Pace", "MK II", "S-Type", "X-Type", "XE", "XF", "XJ", "XJR", "XJS", "XK", "XK8"],
    "Jeep": ["Avenger", "Cherokee", "CJ", "Comanche", "Commander", "Compass", "Gladiator", "Grand Cherokee", "Liberty", "Patriot", "Renegade", "Wagoneer", "Willys", "Wrangler"],
    "Jetour": ["Dashing", "Traveller", "X70", "X90", "X95"],
    "Jinpeng": ["Ami"],
    "Kia": ["Asia Rocsta", "Besta", "Cadenza", "Carens", "Carnival", "Ceed", "Cerato", "Clarus", "Elan", "EV3", "EV5", "EV6", "EV9", "Joice", "Leo", "Magentis", "Mentor", "Niro", "Opirus", "Optima", "Picanto", "Pregio", "Pride", "ProCeed", "Retona", "Rio", "Roadster", "Rocsta", "Sedona", "Sephia", "Shuma", "Sorento", "Soul", "Spectra", "Sportage", "Stinger", "Stonic", "Telluride", "Venga", "XCeed"],
    "Koenigsegg": ["CC8S", "CCR", "CCX", "CCXR", "Agera", "Agera R", "Agera S", "Agera RS", "Agera Final", "One:1", "Regera", "Jesko", "Jesko Absolut", "Gemera", "Quant", "CC850", "TreVita", "Ragnarok"],
    "KTM": ["X-BOW"],
    "Lada": ["110", "111", "112", "1117", "1118", "1119", "1200", "1300", "1500", "2101", "2103", "2104", "2105", "2106", "2107", "2108", "2109", "2110", "2111", "2112", "2170", "Aleko", "Forma", "Granta", "Kalina", "Niva", "Nova", "Priora", "Samara"],
    "Lamborghini": ["Aventador", "Countach", "Diablo", "Espada", "Gallardo", "Huracan", "Jalpa", "LM", "Miura", "Murcielago", "Urraco", "Urus"],
    "Lancia": ["Beta", "Dedra", "Delta", "Flamina", "Fulvia", "Gamma", "Kappa", "Lybra", "Musa", "Phedra", "Prisma", "Stratos", "Thema", "Thesis", "Voyager", "Ypsilon", "Zeta"],
    "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
    "Leapmotor": ["C01", "C11"],
    "LEVC": ["TX"],
    "Lexus": ["CT", "ES", "GS", "GX", "HS 250h", "IS", "LBX", "LC", "LFA", "LM", "LS", "LX", "NX", "RC", "RX", "RZ", "SC", "TX", "UX"],
    "Ligier": ["Altul", "Ambra", "Be-Two", "Be-Up", "IXO", "JS RC", "JS49", "JS50", "JS50L", "JS60", "Nova", "Optima", "X-Too", "X-Too Max", "X-Too R", "X-Too RS", "X-Too S"],
    "Lincoln": ["Aviator", "Continental", "Corsair", "LS", "Mark", "Mark LT", "MKC", "MKX", "MKZ", "Nautilus", "Navigator", "Town Car"],
    "Lixiang": ["L7", "L9"],
    "Lotus": ["340R", "Cortina", "Elan", "Eletre", "Elise", "Elite", "Emeya", "Emira", "Esprit", "Europa", "Evora", "Excel", "Exige", "Super Seven", "V8"],
    "LTI": ["Fairway", "TX2", "TX4"],
    "Lucid": ["Air", "Gravity"],
    "Lync & Co": ["01", "02", "03"],
    "MAN": ["TGE"],
    "Maserati": ["224", "3200", "Biturbo", "Coupe", "Ghibli", "GranCabrio", "Gransport", "GranTurismo", "Grecale", "Levante", "MC20", "MC20 Cielo", "Merak", "Quattroporte", "Shamal", "Spyder"],
    "Maxus": ["eT90", "Euniq 5", "Euniq 6", "MIFA 9"],
    "Maybach": ["57", "62"],
    "Mazda": ["2", "3", "5", "6", "121", "323", "323F", "626", "929", "Bongo", "BT-50", "CX-3", "CX-5", "CX-7", "CX-9", "CX-30", "CX-50", "CX-60", "CX-80", "CX-90", "Demio", "Millenia", "MPV", "MX-3", "MX-5", "MX-6", "MX-30", "Premacy", "Protege", "RX-6", "RX-7", "RX-8", "B Series", "E Series", "Tribute", "Xedos"],
    "McLaren": ["570 GT", "570S Coupe", "600LT Coupe", "600LT Spider", "650S", "675LT", "720S Coupe", "720S Spider", "765LT Spider", "altul", "Artura", "GT", "MP4-12C"],
    "Mercedes-Benz": ["280", "AMG GT", "Citan", "CL", "CLA", "CLC", "CLE", "CLK", "CLS", "EQA", "EQB", "EQC", "EQE", "EQS", "EQS 680 SUV", "EQT", "EQV", "GL", "GLA", "GLB", "GLC", "GLE", "GLK", "GLS", "A Class", "B Class", "C Class", "E Class", "G Class", "R Class", "S Class", "T Class", "V Class", "X Class", "Maybach GLS", "Maybach S Class", "Maybach SL 680", "MB 100", "ML", "Monarch", "SL", "SLC", "SLK", "SLR", "SLS", "Sprinter", "Vaneo", "Vario", "Viano", "Vito", "W123", "W124 (1984-1993)", "W201 (190)"],
    "Mercury": ["Comet", "Cougar", "Marauder", "Mariner", "Marquis", "Milan", "Montego", "Monterey", "Mountaineer", "Sable", "Tracer", "Villager", "Zephyr"],
    "MG": ["4", "5", "Cyberster", "EHS", "HS", "Marvel R", "MG3", "MGB", "MGF", "Midget", "ZS", "ZT"],
    "Microcar": ["Cargo", "DUE", "DUE First", "Flex", "Highland X", "Ligier", "M.Cross", "M.GO", "MC", "Virgo"],
    "MINI": ["1000", "1300", "Aceman", "Clubman", "Cooper", "Cooper S", "Countryman", "John Cooper Works", "ONE", "Paceman"],
    "Mitsubishi": ["3000GT", "ASX", "Canter", "Carisma", "Colt", "Cordia", "Cosmos", "Diamante", "Eclipse", "Eclipse Cross", "Endeavor", "FTO", "Galant", "Galloper", "Grandis", "i-MiEV", "L200", "L300", "L400", "Lancer", "Lancer Evolution", "Montero", "Outlander", "Pajero", "Pajero Pinin", "Pajero Sport", "Santamo", "Sapporo", "Sigma", "Space Gear", "Space Runner", "Space Star", "Space Wagon", "Starion", "Tredia"],
    "Morgan": ["Plus 4"],
    "NIO": ["el7", "et5", "et7"],
    "Nissan": ["100 NX", "200 SX", "240 SX", "280 ZX", "300 ZX", "350 Z", "370 Z", "Almera", "Almera Tino", "Altima", "Ariya", "Armada", "Bluebird", "Cherry", "Cube", "Frontier", "GT-R", "Interstar", "Juke", "King Cab", "Kubistar", "Laurel", "Leaf", "Maxima", "Micra", "Murano", "Navara", "Note", "NP300 Pickup", "NV200", "NV300", "NV400", "Pathfinder", "Patrol", "Pickup", "Pixo", "Prairie", "Primastar", "Primera", "Pulsar", "Qashqai", "Qashqai+2", "Quest", "Rouge", "Sentra", "Serena", "Silvia", "Skyline", "Stanza", "Sunny", "Terrano", "Tiida", "Titan", "Townstar", "Trade", "Urvan", "Vanette", "X-Trail", "Xterra"],
    "Nysa": ["500 Series", "N Series"],
    "Oldsmobile": ["Alero", "Aurora", "Bravada", "Custom Cruiser", "Cutlass", "Delta 88", "Eighty - Eight", "Intrigue", "Silhouette", "Supreme", "Toronado"],
    "Omoda": ["5", "7", "9", "E5"],
    "Opel": ["Adam", "Agila", "Ampera", "Antara", "Arena", "Ascona", "Astra", "Calibra", "Campo", "Cascada", "Combo", "Commodore", "Corsa", "Crossland", "Crossland X", "Diplomat", "Frontera", "Grandland", "Grandland X", "GT", "Insignia", "Kadett", "Karl", "Manta", "Meriva", "Mokka", "Monterey", "Monza", "Movano", "Nova", "Omega", "Pick up Sportcap", "Rekord", "Senator", "Signum", "Sintra", "Speedster", "Tigra", "Vectra", "Vivaro", "Zafira"],
    "Pagani": ["Zonda C12", "Zonda S", "Zonda F", "Zonda R", "Zonda Cinque", "Zonda Tricolore", "Zonda Revolucion", "Huayra", "Huayra BC", "Huayra Roadster", "Huayra BC Roadster", "Huayra R", "Huayra Codalunga", "Huayra Imola", "Utopia"],
    "Peugeot": ["104", "106", "107", "108", "204", "205", "206", "206 CC", "206 plus", "207", "207 CC", "208", "301", "304", "305", "306", "307", "307 CC", "308", "308 CC", "309", "395", "404", "405", "406", "407", "408", "504", "505", "508", "604", "605", "607", "806", "807", "1007", "2008", "3008", "4007", "4008", "5008", "Bipper", "Boxer", "E-5008", "Expert", "iOn", "Partner", "RCZ", "Rifter", "Traveller"],
    "Piaggio": ["Porter"],
    "Plymouth": ["Belvedere", "Caravelle", "Duster", "Fury", "Gran Fury", "Grand Voyager", "GTX", "Horizon", "Laser", "Prowler", "Road Runner", "Satellite", "Superbird", "Turismo", "Valiant", "Voyager"],
    "Polestar": ["1", "2", "3"],
    "Polonez": ["1.5", "1.6", "Atu", "Caro"],
    "Pontiac": ["1000", "6000", "Bonneville", "Catalina", "Chieftain", "Fiero", "Firebird", "G6", "Grand-Am", "Grand-Prix", "GTO", "Le Mans", "Montana", "Solstice", "Sunbird", "Sunfire", "Trans Am", "Trans Sport", "Vibe"],
    "Porsche": ["356", "718 Boxster", "718 Cayman", "718 Spyder", "911", "912", "914", "924", "928", "944", "959", "962", "968", "Boxster", "Carrera GT", "Cayenne", "Cayman", "Macan", "Panamera", "Taycan"],
    "RAM": ["1500", "2500", "3500"],
    "Renault": ["4", "5", "8", "9", "10", "11", "12", "14", "18", "19", "20", "21", "25", "30", "Alaskan", "Alpine A110", "Alpine A310", "Alpine V6", "Arkana", "Austral", "Avantime", "Captur", "Clio", "Coupe", "Espace", "Express", "Fluence", "Fuego", "Grand Espace", "Grand Scenic", "Kadjar", "Kangoo", "Koleos", "Laguna", "Latitude", "Master", "Megane", "Modus", "Rafale", "Safrane", "Scenic", "Scenic Conquest", "Scenic RX4", "Symbioz", "Talisman", "Thalia", "Trafic", "Twingo", "Twizy", "Vel Satis", "Wind", "Zoe"],
    "Rimac": ["Concept One", "Concept S", "C_Two", "Nevera", "Verne"],
    "Rolls-Royce": ["Corniche", "Cullinan", "Dawn", "Flying Spur", "Ghost", "Park Ward", "Phantom", "Silver Cloud", "Silver Dawn", "Silver Seraph", "Silver Shadow", "Silver Spirit", "Silver Spur", "Spectre", "Touring Limousine", "Wraith"],
    "Rover": ["25", "45", "75", "100", "111", "114", "115", "200", "213", "214", "216", "218", "220", "400", "414", "416", "418", "420", "600", "618", "620", "623", "800", "820", "825", "827", "City Rover", "Metro", "MG", "Mini", "Montego", "SD", "Streetwise"],
    "Saab": ["9-2X", "9-3", "9-3X", "9-5", "9-7X", "90", "96", "99", "900", "9000"],
    "SARINI": ["M1", "M1 LUQI", "PIAWA", "X7", "X8", "X9"],
    "Saturn": ["Sky"],
    "Seat": ["Alhambra", "Altea", "Altea XL", "Arona", "Arosa", "Ateca", "Cordoba", "Exeo", "Ibiza", "Inca", "Leon", "Malaga", "Marbella", "Mii", "Ronda", "Tarraco", "Terra", "Toledo"],
    "Seres": ["3", "SF5"],
    "Shuanghuan": ["Sceo"],
    "Skoda": ["100", "105", "120", "130", "135", "Citigo", "Elroq", "Enyaq", "Fabia", "Favorit", "Felicia", "Forman", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Praktik", "RAPID", "Roomster", "Scala", "Superb", "Yeti"],
    "Skywell": ["ET5"],
    "Skyworth": ["CE11", "K", "K-i"],
    "Smart": ["Crossblade", "Forfour", "Fortwo", "Roadster", "Roomster"],
    "SsangYong": ["Actyon", "Family", "Korando", "Kyron", "Musso", "Rexton", "Rodius", "Tivoli", "Tivoli Grand", "Torres", "XLV"],
    "Subaru": ["1800 Coupe", "Ascent", "B9 Tribeca", "Baja", "BRZ", "Crosstrek", "Forester", "G3X Justy", "Impreza", "Justy", "Legacy", "Leone", "Levorg", "Outback", "Solterra", "SVX", "Trezia", "Tribeca", "Vivio", "WRX", "XT", "XV"],
    "Suzuki": ["Across", "Alto", "Baleno", "Cappuccino", "Carry", "Celerio", "Fronx", "Grand Vitara", "Ignis", "Jimny", "Kizashi", "Liana", "LJ", "Reno", "Samurai", "SJ", "Splash", "Super-Carry", "Swace", "Swift", "SX4", "SX4 S-Cross", "Vitara", "Wagon R+", "X-90", "XL7"],
    "Syrena": ["101", "102", "103", "104", "105", "Bosto", "R-20"],
    "Tata": ["Indica", "Indigo", "Nano", "Safari", "Xenon"],
    "Tesla": ["Cybertruck", "Model 3", "Model S", "Model X", "Roadster", "Y"],
    "Toyota": ["4-Runner", "Auris", "Avalon", "Avensis", "Avensis Verso", "Aygo", "Aygo X", "bZ4X", "C-HR", "Camry", "Camry Solara", "Carina", "Celica", "Corolla", "Corolla Cross", "Corolla Verso", "Cressida", "Crown", "Dyna", "FJ", "GR86", "Grand Highlander", "GT86", "Hiace", "Highlander", "Hilux", "iQ", "Land Cruiser", "Lite-Ace", "Matrix", "Mirai", "MR2", "Paseo", "Picnic", "Previa", "Prius", "Prius+", "ProAce", "Proace City", "Proace City Verso", "Proace Verso", "RAV4", "Sequoia", "Sienna", "Starlet", "Supra", "Tacoma", "Tercel", "Tundra", "Urban Cruiser", "Venza", "Verso", "Verso S", "Yaris", "Yaris Cross", "Yaris Verso"],
    "Trabant": ["601", "P 50"],
    "Triumph": ["Dolomite", "Moss", "Spitfire", "TR3", "TR4", "TR5", "TR6", "TR7", "TR8"],
    "Uaz": ["452", "469 B", "3153", "3162"],
    "Vauxhall": ["Astra", "Frontera", "Omega", "Vectra", "Vivaro"],
    "Volkswagen": ["181", "Amarok", "Arteon", "Atlas", "Beetle", "Bora", "Buggy", "Caddy", "California", "Caravelle", "CC", "Corrado", "Eos", "Fox", "Golf", "Golf Plus", "Golf Sportsvan", "ID.Buzz", "ID.3", "ID.4", "ID.5", "ID.6", "ID.7", "Iltis", "Jetta", "Kafer", "Karmann Ghia", "LT", "Lupo", "Multivan", "New Beetle", "Passat", "Passat Alltrack", "Passat CC", "Phaeton", "Polo", "Polo Cross", "Routan", "Santana", "Scirocco", "Sharan", "T-Cross", "T-Roc", "Taigo", "Tayron", "Teramont", "Tiguan", "Tiguan Allspace", "Touareg", "Touran", "Transporter", "up!", "Vento"],
    "Volvo": ["245", "262", "340", "744", "745", "780", "850", "855", "945", "965", "C30", "C40", "C70", "EX30", "EX90", "MY23", "P1800", "Polar", "S40", "S60", "S70", "S80", "S90", "200 Series", "300 Series", "400 Series", "700 Series", "900 Series", "V40", "V40 Cross Country", "V50", "V60", "V60 Cross Country", "V70", "V90", "V90 Cross Country", "XC40", "XC60", "XC70", "XC90"],
    "Voyah": ["Dream", "Free"],
    "Warszawa": ["203", "204", "223", "224", "M-20", "Pick-up"],
    "Wartburg": ["1.3", "311", "312", "313", "353"],
    "Wołga": ["2410", "GAZ-21", "GAZ-24"],
    "Xiaomi": ["SU7"],
    "XPeng": ["G3i", "G9", "P5", "P7"],
    "Zaporożec": ["965", "968"],
    "Zastava": ["750", "1100"],
    "ZEEKR": ["001", "007", "009", "X"],
    "Zenvo": ["ST1", "TS1", "TSR", "TSR-S", "TS1 GT", "TSR GT", "ST1 50S", "TSR-S 50S"],
    "Zhidou": ["D1", "D2", "D3", "KWB"],
};